# Add account credentials and API keys here.
# AWS S3 details
AWS_ACCESS_KEY_ID: "AKIAJLEMOV7VUQW6N6WA"
AWS_SECRET_ACCESS_KEY: "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"
AWS_S3_BUCKET: "images-paraginfotech"

# AWS_ACCESS_KEY_ID: "AKIAI3IG4JKQTJYAIY3Q"
# AWS_SECRET_ACCESS_KEY: "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"
# AWS_S3_BUCKET: "skipper-edu"




